"""Shared Pydantic data models for FutureBench-Finance artifacts."""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class EvidenceItem(BaseModel):
    """Evidence captured during reasoning (e.g., Polymarket snapshot, EDGAR fact)."""

    model_config = ConfigDict(extra="ignore")

    type: str
    source: str
    snippet: Optional[str] = None
    timestamp: Optional[datetime] = None


class PredictionPayload(BaseModel):
    """Probability and rationale bundle emitted by the purple agent."""

    model_config = ConfigDict(extra="ignore")

    probability: float = Field(ge=0.0, le=1.0)
    rationale: Optional[list[EvidenceItem]] = None
    analysis: Optional[str] = None


class PredictionMetadata(BaseModel):
    """Metadata describing the purple agent instance and runtime."""

    model_config = ConfigDict(extra="ignore")

    model: str
    timestamp: datetime
    version: Optional[str] = None
    predictor_id: Optional[str] = None


class PredictionRecord(BaseModel):
    """Schema for each JSONL row produced by the purple agent."""

    model_config = ConfigDict(extra="ignore")

    id: str
    prediction: PredictionPayload
    metadata: Optional[PredictionMetadata] = None


class EventSpec(BaseModel):
    """Event descriptor generated by the ingestion pipeline."""

    model_config = ConfigDict(extra="ignore")

    id: str
    question: str
    domain: Optional[str] = None
    resolution_date: Optional[datetime] = None
    source: Optional["EventSource"] = None
    ground_truth_source: Optional[str] = None
    forecast_horizon_days: Optional[int] = None
    tags: list[str] = Field(default_factory=list)
    baseline_probability: Optional[float] = None


class EventSource(BaseModel):
    """Origin metadata for an event (Polymarket, EDGAR calendar, etc.)."""

    model_config = ConfigDict(extra="ignore")

    type: str
    market_id: Optional[str] = None
    url: Optional[str] = None
    resolution_date: Optional[datetime] = None


class ResolutionRecord(BaseModel):
    """Ground-truth record consumed by the evaluator."""

    model_config = ConfigDict(extra="ignore")

    id: str
    outcome: int = Field(ge=0, le=1)
    verified_value: Optional[float] = None
    verified_source: Optional[str] = None
    resolved_at: Optional[datetime] = None
